/**
 * bo-dreaming — nightly distillation of reviewer blocks into recurring patterns.
 *
 * Ports v1's `runDreamingDistillation()` from src/reviewer.ts. Concept:
 * concrete past failures (every reviewer block recorded in this DB) cluster
 * into recurring patterns better than abstract rules. A nightly Sonnet pass
 * reads them, clusters, and writes the distilled output to
 * wiki/personal/bo-reviewer-patterns.md — which the bo-adversarial-reviewer
 * skill reads alongside bo-mistakes.md before every qualifying Slack send.
 *
 * Source data: a small `bo_reviewer_blocks` table populated by the
 * bo-reviewer-enforcement plugin whenever a host-side review verdict was
 * not "ok". Each row: timestamp, original text, verdict reason, applied fix.
 */
import fs from 'fs';
import path from 'path';
import Anthropic from '@anthropic-ai/sdk';
import { getDb } from '../../db/connection.js';
import { readEnvFile } from '../../env.js';
import { log } from '../../log.js';

const PATTERNS_PATH = '/Users/joel/Brain/xtra/wiki/personal/bo-reviewer-patterns.md';
const DREAM_MODEL = 'claude-sonnet-4-6';
const DREAM_INTERVAL = 24 * 60 * 60 * 1000;
const STARTUP_DELAY = 2 * 60 * 1000;

interface BlockRow {
  ts: string;
  original_text: string;
  reason: string;
  fix_applied: string | null;
}

function ensureBlocksTable(): void {
  try {
    getDb().exec(`
      CREATE TABLE IF NOT EXISTS bo_reviewer_blocks (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        ts TEXT NOT NULL,
        session_id TEXT,
        original_text TEXT NOT NULL,
        reason TEXT NOT NULL,
        fix_applied TEXT
      );
      CREATE INDEX IF NOT EXISTS idx_bo_reviewer_blocks_ts ON bo_reviewer_blocks(ts);
    `);
  } catch (err) {
    log.warn('bo-dreaming: ensureBlocksTable failed', { err });
  }
}

async function distill(): Promise<void> {
  ensureBlocksTable();
  try {
    const rows = getDb()
      .prepare(`SELECT ts, original_text, reason, fix_applied FROM bo_reviewer_blocks ORDER BY ts DESC LIMIT 200`)
      .all() as BlockRow[];

    if (rows.length < 3) {
      log.debug('bo-dreaming: fewer than 3 blocks, skipping distillation');
      return;
    }

    const env = readEnvFile(['ANTHROPIC_API_KEY', 'CLAUDE_CODE_OAUTH_TOKEN']);
    const client = env.CLAUDE_CODE_OAUTH_TOKEN
      ? new Anthropic({ authToken: env.CLAUDE_CODE_OAUTH_TOKEN })
      : env.ANTHROPIC_API_KEY
        ? new Anthropic({ apiKey: env.ANTHROPIC_API_KEY })
        : null;
    if (!client) {
      log.warn('bo-dreaming: no creds — skipping');
      return;
    }

    const corpus = rows
      .map(
        (r) =>
          `## ${r.ts}\nreason: ${r.reason}\noriginal: ${r.original_text.slice(0, 400)}\nfix: ${r.fix_applied?.slice(0, 200) ?? '(none)'}\n`,
      )
      .join('\n')
      .slice(-30_000);

    const prompt = `Below is a log of times Bo (an AI assistant) was caught by a quality auditor for substituting close-enough alternatives, claiming completion without action, dropping scope, or hiding blockers.

Cluster these into 3-7 recurring failure patterns. For each pattern, give:
- A short name (2-4 words)
- A 1-sentence description of when it triggers
- A concrete example from the log
- The honest behavior Bo should have done instead

Output as a markdown document for Bo to read at startup. No preamble. No conclusion. Just the patterns.

# RAW BLOCKS
${corpus}`;

    const result = await client.messages.create({
      model: DREAM_MODEL,
      max_tokens: 2048,
      messages: [{ role: 'user', content: prompt }],
    });
    const block = result.content.find((b) => b.type === 'text');
    if (!block || block.type !== 'text') return;
    const text = block.text.trim();
    if (!text) return;

    fs.mkdirSync(path.dirname(PATTERNS_PATH), { recursive: true });
    const header = `<!-- AUTO-GENERATED by bo-dreaming. Distilled from bo_reviewer_blocks.\nLast run: ${new Date().toISOString()}. Do not edit manually — overwritten next run. -->\n\n# Bo Reviewer Patterns\n\n`;
    fs.writeFileSync(PATTERNS_PATH, header + text + '\n');
    log.info('bo-dreaming: distillation complete', {
      path: PATTERNS_PATH,
      bytes: text.length,
      sourceRows: rows.length,
    });
  } catch (err) {
    log.warn('bo-dreaming: distillation failed', { err });
  }
}

export default async function init(): Promise<void> {
  ensureBlocksTable();
  setTimeout(() => void distill(), STARTUP_DELAY).unref?.();
  setInterval(() => void distill(), DREAM_INTERVAL).unref?.();
  log.info('bo-dreaming: scheduled nightly reviewer-pattern distillation');
}
